### ISSUE TITLE
Implement Google site tracking

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#30]
All pages/calls should be tracked. Google site tracking id: `UA-572981-2`. Previous code:

```
 <!-- Google -->   
   <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-572981-2', 'auto');
      ga('send', 'pageview');
  </script>
<!-- End of Google -->
```

**Comment by ptoussai** [comment]
Added in 7a8577cef027dc0e181454e46c8399afc02d9c7d
I also changed the sidebar links to be basic <a/> links. The reason is that using <Link/> from next.js does not load a new page from the browser perspective. GA has a way to deal with this (tracking the history) but then possibly all sort of transitions will be tracked.

**Comment by ptoussai** [comment]
@mbaudis Could you check if it works?

**Comment by mbaudis** [comment]
AFAIK o.k.; can track the hits on Google.
