### ISSUE TITLE
Bug: "More than 1 `datasetIds` value was provided." on beacon+

### ISSUE THREAD

**Issue by ptoussai** [progenetix/progenetix-web#41]
When selecting more than one dataset in beacon+ the collation api respond: "More than 1 `datasetIds` value was provided."
This used to work with the previous api.

Possible solutions: 
 a) enable this feature on the new api
 b) create a work around client side (not completely easy)
 c) remove the use case, i.e. it will be possible to select only one dataset (easiest!)

**Comment by mbaudis** [comment]
This is due to the changed structure where - except Beacon/bycon itself - only 1 data set is now supported. So, 

* Beacon calls will have to provide, accept multiple datasets
* other parts will receive unscoped responses (e.g. the responses are not labeled for a dataset)

Where does this become problematic?

**Comment by mbaudis** [comment]
Fixed(?). One can now have multiple dasetIds, and the counts will be added. Still, the response will not scope the filters to individual datasets.

**Comment by ptoussai** [comment]
Yes, it works now! Closing.
