### ISSUE TITLE
Error: Beacon+ example load error (reload)

### ISSUE THREAD

**Issue by mbaudis** [progenetix/progenetix-web#58]
Currently the examples for Beacon+ queries https://progenetix.org/ui/ are not loading into the form if the form had been called directly through this URL or through https://progenetix.org/beacon-plus/search.html?. Here, clicking an example button just reloads the page.

This option works if the Beacon+ page has been accessed from the Progenetix pages, though URL looks the same. Some preload issue?

**Comment by ptoussai** [comment]
The problem seems to be related to the `.html` in the URL. It seems to confuse the router somehow, hence the reload. This is not correct and the URL should be just [https://progenetix.org/beacon-plus/search](https://progenetix.org/beacon-plus/search). This works.

[https://progenetix.org/ui/ ](https://progenetix.org/ui/ ) does not work for me.

**Comment by mbaudis** [comment]
Thanks - that was it (also: I had a wrong link above -  https://beacon.progenetix.org/ui/ ; doesn't work w/o the subdomain anyway).
